// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLffPCv3l-hrr8zGcySJNDCQwLcfmZLA',
    appId: '1:820679207899:web:4710688c2c8c25141a15fe',
    messagingSenderId: '820679207899',
    projectId: 'goal-acd6f',
    authDomain: 'goal-acd6f.firebaseapp.com',
    storageBucket: 'goal-acd6f.firebasestorage.app',
    measurementId: 'G-VC6GZ80RSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7ppt5hibdwmlT0iX3NFATpHvdnvxqD4',
    appId: '1:820679207899:android:6f81dae4e745d2971a15fe',
    messagingSenderId: '820679207899',
    projectId: 'goal-acd6f',
    storageBucket: 'goal-acd6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzTYNEF70XKFNocqjWUxODvW-HEm2qjM8',
    appId: '1:820679207899:ios:f89ca2da974038041a15fe',
    messagingSenderId: '820679207899',
    projectId: 'goal-acd6f',
    storageBucket: 'goal-acd6f.firebasestorage.app',
    iosClientId: '820679207899-pnlqjvihvmhr9n3pof2m8jjgctervo6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.goal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzTYNEF70XKFNocqjWUxODvW-HEm2qjM8',
    appId: '1:820679207899:ios:f89ca2da974038041a15fe',
    messagingSenderId: '820679207899',
    projectId: 'goal-acd6f',
    storageBucket: 'goal-acd6f.firebasestorage.app',
    iosClientId: '820679207899-pnlqjvihvmhr9n3pof2m8jjgctervo6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.goal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnLffPCv3l-hrr8zGcySJNDCQwLcfmZLA',
    appId: '1:820679207899:web:70a2bfefc5e481e31a15fe',
    messagingSenderId: '820679207899',
    projectId: 'goal-acd6f',
    authDomain: 'goal-acd6f.firebaseapp.com',
    storageBucket: 'goal-acd6f.firebasestorage.app',
    measurementId: 'G-S8832PN9KD',
  );
}
